### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by SirNerdsAlot5** [DeekyJay/SoundwaveInteractive-releases#8]
My buttons will not save here: https://mixer.com/lab

And Soundwave will not connect to my mixer account either.

And the ia32 installer is viewed as a virus.

**Comment by DeekyJay** [comment]
@SirNerdsAlot5 You no longer use the lab, go to https://mixer.com/i/studio
Also, ia32 is for 32-bit and shouldn't be used unless it's the only option. It's also definitely not a virus, but your anti-virus might assume because it's from an unknown publisher.
If you're having issues with logging in. Go to your Oauth section on Mixer and remove Soundwave, and try to re-login.
